# Generated by Django 4.1.3 on 2022-11-24 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='features',
            new_name='featured',
        ),
    ]
